apiVersion: v1
kind: Service
metadata:
  name: allpodd
  labels:
    app: allpodd
    app.kubernetes.io/name: allpodd
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: ProsjektBTS
    app.kubernetes.io/managed-by: kubectl
  annotations:
    security.usn.no/bidrag_tekst: "OFFENTLIG_INNHOLD – Anonym visning. Ikke koblet til identitet."
    security.usn.no/pseudonym: "KUN_ADMINISTRATOR – Pseudonym synlig kun for administrator."
spec:
  type: NodePort
  selector:
    app: allpodd
  ports:
    - name: "80"
      nodePort: 31793
      port: 80
      targetPort: 80
    - name: "81"
      nodePort: 32753
      port: 81
      targetPort: 81
---
apiVersion: v1
kind: Pod
metadata:
  name: allpodd
  labels:
    app: allpodd
    app.kubernetes.io/name: allpodd
    app.kubernetes.io/instance: allpodd-prod
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: ProsjektBTS
    app.kubernetes.io/managed-by: kubectl
  annotations:
    security.usn.no/kommentar: "PRIVAT_INNHOLD – Kun synlig for autentisert bruker. Ikke koblet til pseudonym i frontend."
    security.usn.no/pseudonym: "KUN_ADMINISTRATOR – Ikke tilgjengelig i API eller frontend. Kun for admin."
    security.usn.no/bidrag_tekst: "OFFENTLIG_INNHOLD – Visning uten kobling til identitet. Pseudonym vises kun for administratorer."
    infra.usn.no/secrets: "DRIFT_KRITISK_SENSITIV – Secrets håndteres via Kubernetes og er RBAC-beskyttet."
spec:
  containers:
    - name: app
      image: localhost/app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 80
        - containerPort: 81
      stdin: true
      tty: true
      env:
        - name: TERM
          value: xterm

    - name: bidrag-db
      image: localhost/bidrag-db:latest
      imagePullPolicy: Never
      stdin: true
      tty: true
      env:
        - name: TERM
          value: xterm
      volumeMounts:
        - mountPath: "/var/www/bidrag"
          name: "bidrag-data"

    - name: pseudonym-db
      image: localhost/pseudonym-db:latest
      imagePullPolicy: Never
      stdin: true
      tty: true
      env:
        - name: TERM
          value: xterm
      volumeMounts:
        - mountPath: "/var/www/pseudonym"
          name: "pseudonym-data"

    - name: web
      image: localhost/web:latest
      imagePullPolicy: Never
      stdin: true
      tty: true
      env:
        - name: TERM
          value: xterm

  volumes:
    - name: "bidrag-data"
      persistentVolumeClaim:
        claimName: bidrag-pvc
    - name: "pseudonym-data"
      persistentVolumeClaim:
        claimName: pseudonym-pvc

