apiVersion: v1
kind: Service
metadata:
  labels:
    app: allpodd
  name: allpodd
spec:
  ports:
    - name: "80"
      nodePort: 31793
      port: 80
      targetPort: 80
    - name: "81"
      nodePort: 32753
      port: 81
      targetPort: 81
  selector:
    app: allpodd
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: allpodd
  name: allpodd
spec:
  containers:
    - name: app
      image: localhost/app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 80
        - containerPort: 81
      stdin: true
      tty: true
      env:
        - name: TERM
          value: xterm

    - name: bidrag-db
      image: localhost/bidrag-db:latest
      imagePullPolicy: Never
      stdin: true
      tty: true
      env:
        - name: TERM
          value: xterm
      volumeMounts:
        - name: bidrag-volume
          mountPath: /data

    - name: pseudonym-db
      image: localhost/pseudonym-db:latest
      imagePullPolicy: Never
      stdin: true
      tty: true
      env:
        - name: TERM
          value: xterm

    - name: web
      image: localhost/web:latest
      imagePullPolicy: Never
      stdin: true
      tty: true
      env:
        - name: TERM
          value: xterm

  volumes:
    - name: bidrag-volume
      hostPath:
        path: /home/brukernavn/v24-25.1/ProsjektBTS/db
        type: DirectoryOrCreate
