apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-04-29T17:12:04Z"
  labels:
    app: allpodd
  name: allpodd
spec:
  ports:
  - name: "80"
    nodePort: 30492
    port: 80  
    targetPort: 80
  - name: "81"
    nodePort: 31502
    port: 81
    targetPort: 81
  selector:
    app: allpodd
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-04-29T17:12:04Z"
  labels:
    app: allpodd
  name: allpodd
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: localhost/app:latest
    imagePullPolicy: Never
    name: app
    ports:
    - containerPort: 80
    - containerPort: 81
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/bidrag-db:latest
    imagePullPolicy: Never
    name: bidrag-db
    volumeMounts:
    - mountPath: /var/www/bidrag
      name: bidrag-storage
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/pseudonym-db:latest
    imagePullPolicy: Never
    name: pseudonym-db
    volumeMounts:
    - mountPath: /var/www/pseudonym
      name: pseudonym-storage
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/web:latest
    imagePullPolicy: Never
    name: web
    stdin: true
    tty: true
  volumes:
  - name: bidrag-storage
    persistentVolumeClaim:
      claimName: bidrag-pvc
  - name: pseudonym-storage
    persistentVolumeClaim:
      claimName: pseudonym-pvc