apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-04-29T17:12:04Z"
  labels:
    app: allpodd
    app.kubernetes.io/name: allpodd
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: ProsjektBTS
    app.kubernetes.io/managed-by: kubectl
    annotations:
      security.usn.no/bidrag_tekst: "OFFENTLIG_INNHOLD – Anonym visning. Ikke koblet til identitet."
      security.usn.no/pseudonym: "KUN_ADMINISTRATOR – Pseudonym synlig kun for administrator."    
name: allpodd
spec:
  ports:
  - name: "80"
    nodePort: 30492
    port: 80  
    targetPort: 80
  - name: "81"
    nodePort: 31502
    port: 81
    targetPort: 81
  selector:
    app: allpodd
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-04-29T17:12:04Z"
  labels:
    app: allpodd
    app.kubernetes.io/name: allpodd
    app.kubernetes.io/instance: allpodd-prod
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: ProsjektBTS
    app.kubernetes.io/managed-by: kubectl
    annotations:
     security.usn.no/kommentar: "PRIVAT_INNHOLD – Kun synlig for autentisert bruker. Ikke koblet til pseudonym i frontend."
     security.usn.no/pseudonym: "KUN_ADMINISTRATOR – Ikke tilgjengelig i API eller frontend. Kun for admin."
     security.usn.no/bidrag_tekst: "OFFENTLIG_INNHOLD – Visning uten kobling til identitet. Pseudonym vises kun for administratorer."
     infra.usn.no/secrets: "DRIFT_KRITISK_SENSITIV – Secrets håndteres via Kubernetes og er RBAC-beskyttet."
name: allpodd
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: localhost/app:latest
    imagePullPolicy: Never
    name: app
    ports:
    - containerPort: 80
    - containerPort: 81
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/bidrag-db:latest
    imagePullPolicy: Never
    name: bidrag-db
    volumeMounts:
    - mountPath: /var/www/bidrag
      name: bidrag-storage
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/pseudonym-db:latest
    imagePullPolicy: Never
    name: pseudonym-db
    volumeMounts:
    - mountPath: /var/www/pseudonym
      name: pseudonym-storage
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/web:latest
    imagePullPolicy: Never
    name: web
    stdin: true
    tty: true
  volumes:
  - name: bidrag-storage
    persistentVolumeClaim:
      claimName: bidrag-pvc
  - name: pseudonym-storage
    persistentVolumeClaim:
      claimName: pseudonym-pvc