apiVersion: v1
kind: PersistentVolume
metadata:
  name: bidrag-pv
  labels:
    app.kubernetes.io/name: bidrag-db
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: ProsjektBTS
  annotations:
    infra.usn.no/volum: "INFRA_LAGRING_SENSITIV - Lokal lagring for SQLite-data. Kryptert og RBAC-beskyttet."
    security.usn.no/systemdata: "SYSTEM_DATA_SENSITIV - Data slettes iht. datasikkerhetspolicy."
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kasper/ProsjektBTS/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bidrag-pvc
  labels:
    app.kubernetes.io/name: bidrag-db
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: ProsjektBTS
  annotations:
    infra.usn.no/volum: "INFRA_LAGRING_SENSITIV - PVC for databasen. Skal kun brukes av backend-pod."
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
