apiVersion: v1
kind: PersistentVolume
metadata:
  name: bidrag-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/brukernavn/v24-25.1/ProsjektBTS/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bidrag-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
