apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-11-27T09:45:09Z"
  labels:
    app: allpodd
  name: allpodd
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: localhost/app:latest
    imagePullPolicy: Never
    name: app
    ports:
    - containerPort: 80
    - containerPort: 81
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/bidrag-db:latest
    imagePullPolicy: Never
    name: bidrag-db
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/pseudonym-db:latest
    name: pseudonym-db
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/web:latest
    imagePullPolicy: Never
    name: web
    stdin: true
    tty: true
