apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-11-27T09:45:09Z"
  labels:
    app: allpodd
  name: allpodd
spec:
  ports:
  - name: "80"
    nodePort: 30889
    port: 80
    targetPort: 80
  - name: "81"
    nodePort: 30434
    port: 81
    targetPort: 81
  selector:
    app: allpodd
  type: NodePort
